import type { SeedCastPack, SeedNarrativePreset, SeedNpcData } from './types.ts'

export const DEFAULT_STARTER_NPCS: SeedNpcData[] = [
  {
    id: 'npc_xaden',
    name: 'Xaden Riorson',
    role: 'Wingleader / Shadow Wielder',
    gender: 'Male',
    attitude: 'rival',
    affection: 35,
    trust: 40,
    heldWeapon: 'Dual Shadow-Forged Daggers',
    wornArmor: 'Rider Flight Leathers',
    personality: 'Lethal, calculating, fiercely protective of his squad, distrusting of high command.',
    factionId: 'Riders Quadrant',
    description: 'Third-year wingleader and son of the executed rebellion leader.',
  },
  {
    id: 'npc_rhiannon',
    name: 'Rhiannon Matthias',
    role: 'Cadet Companion',
    gender: 'Female',
    attitude: 'friendly',
    affection: 70,
    trust: 75,
    heldWeapon: 'Broadsword & Buckler',
    wornArmor: 'Standard Cadet Leathers',
    personality: 'Loyal, warm-hearted, fearless in physical combat, fiercely supportive.',
    factionId: 'Riders Quadrant',
    description: 'First-year cadet friend bound by mutual survival on the Parapet.',
  },
  {
    id: 'npc_dain',
    name: 'Dain Aetos',
    role: 'Squad Leader / Childhood Friend',
    gender: 'Male',
    attitude: 'allied',
    affection: 65,
    trust: 50,
    heldWeapon: 'Officer Longsword',
    wornArmor: 'Gilded Officer Brigandine',
    personality: 'Rigid by-the-book rule follower, overprotective, conflicted between rules and affection.',
    factionId: 'Riders Quadrant',
    description: 'Second-year squad leader and memory-reader who fears for the protagonist.',
  },
]

export const BUILTIN_CAST_PACKS: SeedCastPack[] = [
  {
    id: 'pack_basgiath',
    name: 'Basgiath Cadet Wing',
    worldTheme: 'Navarre / Fourth Wing',
    description: 'A lethal wingleader, a loyal cadet squadmate, and a rigid rule-bound squad leader.',
    npcs: DEFAULT_STARTER_NPCS,
  },
  {
    id: 'pack_fantasy_vanguard',
    name: 'High Fantasy Vanguard Party',
    worldTheme: 'Epic / Classic Fantasy',
    description: 'A steadfast shield-bearer knight, a mysterious celestial mage, and a swift shadowblade scout.',
    npcs: [
      {
        id: 'npc_valen',
        name: 'Sir Valen Thorne',
        role: 'Vanguard Knight / Guardian',
        gender: 'Male',
        attitude: 'allied',
        affection: 55,
        trust: 65,
        heldWeapon: 'Runed Greatsword & Tower Shield',
        wornArmor: 'Full Plate of the Sun Vanguard',
        personality: 'Stoic, honorable, unyielding shield for his allies, haunted by an oath.',
        description: 'Former palace commander now sworn to protect the protagonist through ancient ruins.',
      },
      {
        id: 'npc_aveline',
        name: 'Lady Aveline Vane',
        role: 'Star-Weaver Arcanist',
        gender: 'Female',
        attitude: 'friendly',
        affection: 60,
        trust: 55,
        heldWeapon: 'Starlight Crystal Staff',
        wornArmor: 'Embroidered Silk Robes',
        personality: 'Curious, sharp-witted, fascinated by forgotten magical lore, slightly haughty.',
        description: 'Exiled high scholar pursuing forbidden astrological secrets.',
      },
      {
        id: 'npc_lyra',
        name: 'Lyra Whisperwind',
        role: 'Shadow Rogue / Scout',
        gender: 'Female',
        attitude: 'neutral',
        affection: 40,
        trust: 45,
        heldWeapon: 'Twin Serrated Daggers',
        wornArmor: 'Midnight Leather Cuirass',
        personality: 'Pragmatic, cynical, moves without sound, always checks exits first.',
        description: 'Guild-trained scout hired for dangerous frontier expeditions.',
      },
    ],
  },
  {
    id: 'pack_court_shadows',
    name: 'Imperial Court & Shadows',
    worldTheme: 'Political / Court Intrigue',
    description: 'A ruthless inquisitor, a charismatic crown heir, and an enigmatic archmage mentor.',
    npcs: [
      {
        id: 'npc_inquisitor_vael',
        name: 'Grand Inquisitor Vael',
        role: 'Imperial Inquisitor / Rival',
        gender: 'Male',
        attitude: 'rival',
        affection: 30,
        trust: 35,
        heldWeapon: 'Executioner Rapier & Iron Rod',
        wornArmor: 'Black Velvet Coat & Armored Gorget',
        personality: 'Cold, highly perceptive, relentlessly suspicious of forbidden power.',
        description: 'Imperial law enforcer hunting for sedition in high court chambers.',
      },
      {
        id: 'npc_prince_aurelius',
        name: 'Crown Prince Aurelius',
        role: 'Royal Heir & Patron',
        gender: 'Male',
        attitude: 'friendly',
        affection: 65,
        trust: 60,
        heldWeapon: 'Gilded Ceremonial Saber',
        wornArmor: 'Lion-Crested Silk & Mail',
        personality: 'Charismatic, ambitious, plays politics with a smile while planning reforms.',
        description: 'Heir to the imperial throne who seeks unconventional allies to secure his claim.',
      },
      {
        id: 'npc_archmage_kaelen',
        name: 'Chancellor Kaelen',
        role: 'Archmage & High Mentor',
        gender: 'Non-binary',
        attitude: 'allied',
        affection: 70,
        trust: 80,
        heldWeapon: 'Focus Ring of Eternity',
        wornArmor: 'Arcane Woven Vestments',
        personality: 'Wise, cryptic, patient, guides with riddles rather than direct commands.',
        description: 'Elder master of the High Spire who recognizes the latent power within the hero.',
      },
    ],
  },
  {
    id: 'pack_grimdark_sellswords',
    name: 'Grimdark Mercenary Band',
    worldTheme: 'Grimdark / Survival',
    description: 'A scarred sellsword captain, a cynical field surgeon, and a deadly crossbow marksman.',
    npcs: [
      {
        id: 'npc_captain_bronn',
        name: 'Captain Bronn Ironjaw',
        role: 'Mercenary Captain',
        gender: 'Male',
        attitude: 'neutral',
        affection: 45,
        trust: 50,
        heldWeapon: 'Notched Warhammer & Broadaxe',
        wornArmor: 'Battered Brigandine & Iron Pot Helmet',
        personality: 'Gruff, battle-hardened, values coin and survival above glorious oaths.',
        description: 'Veteran of a dozen siege wars leading a ragged company of survivors.',
      },
      {
        id: 'npc_sister_maeve',
        name: 'Sister Maeve',
        role: 'Field Alchemist & Medic',
        gender: 'Female',
        attitude: 'friendly',
        affection: 60,
        trust: 65,
        heldWeapon: 'Bone Cleaver & Cautery Iron',
        wornArmor: 'Blood-Stained Leather Apron',
        personality: 'Blunt, unsqueamish, dark sense of humor, deeply compassionate in secret.',
        description: 'Former temple healer who left the cloister to patch up frontline wounded.',
      },
      {
        id: 'npc_jax_vulture',
        name: 'Jax "The Vulture"',
        role: 'Crossbow Marksman',
        gender: 'Male',
        attitude: 'rival',
        affection: 35,
        trust: 40,
        heldWeapon: 'Heavy Lever Crossbow',
        wornArmor: 'Camouflaged Fur & Studded Hide',
        personality: 'Quiet, greedy, deadly accurate, speaks only when naming a target or a price.',
        description: 'Sharpshooter scout whose bolts find eye slits and neck joints.',
      },
    ],
  },
]

export const BUILTIN_NARRATIVE_PRESETS: SeedNarrativePreset[] = [
  {
    id: 'narrative_parapet',
    name: 'The Crucible of the Parapet',
    titleTemplate: "{hero}'s Conscription",
    description: 'Deadly entrance trial atop storm-lashed stone heights with immediate life-or-death peril.',
    openingHook:
      'Standing at the threshold of the rain-slicked Parapet, hundreds of feet above the jagged rocks of the valley below. High winds whip across the narrow stone walkway, and one false step means instant death.',
    narrationStyle:
      'Visceral close-third POV, breathless pacing during peril, sensory focus on the roaring wind, cold rain, and adrenaline spikes.',
  },
  {
    id: 'narrative_frontier_ambush',
    name: 'Frontier Wilderness Ambush',
    titleTemplate: "{hero}'s Trial by Fire",
    description: 'Sudden deadly skirmish in the untamed borderlands surrounded by howling foes.',
    openingHook:
      'A sudden rain of burning arrows shatters the twilight quiet of the misty pine forest. The vanguard caravan ahead is in flames, and shadowy figures emerge from the tree line with drawn steel.',
    narrationStyle:
      'Gritty tactical pacing, visceral physical impact, urgent commands shouted through smoke, mud, and steel clash.',
  },
  {
    id: 'narrative_court_betrayal',
    name: 'Shadows of the High Court',
    titleTemplate: "{hero}'s Reckoning",
    description: 'Clandestine escape or duel following an accusation of high treason in gilded towers.',
    openingHook:
      'The grand council doors slam shut and the herald announces an indictment for high treason. Palace guards in gilded plate step forward with drawn halberds as whispers erupt across the balcony.',
    narrationStyle:
      'Sharp, tense dialogue, subtle psychological tension, keen observation of noble body language, poison in smiles.',
  },
  {
    id: 'narrative_dungeon_gateway',
    name: 'The Sealed Crypt Threshold',
    titleTemplate: "Chronicles of the Deep: {hero}",
    description: 'Standing before an ancient monolith seal as glowing runes ignite in the dark depths.',
    openingHook:
      'Torchlight flickers against a colossal stone monolith buried beneath the mountains. As your blood touches the ancient keystone, azure runes ignite across the surface and the ground begins to tremble.',
    narrationStyle:
      'Atmospheric dread, evocative descriptions of ancient architecture, echoes in the dark, mounting mystical wonder.',
  },
  {
    id: 'narrative_solo_awakening',
    name: 'Solo Ascendant Awakening',
    titleTemplate: "{hero}: The Sovereign Ascendant",
    description: 'A miraculous survival followed by an overwhelming surge of dormant power and awakening.',
    openingHook:
      'Left for dead amidst the burning ruins of the lower quarter, a cold azure pulse suddenly surges through your veins, stitching shattered bones together as a glowing cosmic interface flickers to life.',
    narrationStyle:
      'High-impact cinematic progression, crisp focus on internal mana flow and sensory awakening, unyielding resolve.',
  },
]
